resource_allocator:
  max_disk_mb: 30720  # maximum MB for disk offload (30 GB)
  compress_offload: true  # store offloaded tensors in float16
  min_gpu_tensor_mb: 0.0  # send all tensors to GPU regardless of size
  ram_offload_threshold: 0.9  # offload tensors to disk when RAM usage exceeds this ratio
  vram_offload_threshold: 0.9  # move tensors off GPU when VRAM usage exceeds this ratio
  disk_usage_threshold: 0.95  # stop offloading when disk usage exceeds this ratio
autoplugin:
  decision_interval: 1  # steps between plugin selector decisions
decision_controller:
  budget: 10.0  # maximum total cost for selected actions
max_flat_steps: 5  # consecutive zero-delta steps before pruning/connection
auto_scale_targets: false  # scale tiny targets to match output magnitude
auto_max_steps_interval: 10  # recompute wanderer max_steps every N datapairs
reward_shaper:
  window_size: 10  # number of recent steps for OLS
