resource_allocator:
  max_disk_mb: 20480  # maximum MB for disk offload (20 GB)
  compress_offload: true  # store offloaded tensors in float16
  min_gpu_tensor_mb: 1.0  # tensors smaller than this stay on CPU
